# Learn with Agrisiti - Mobile Learning Application
#
# Agrisiti Academy Mobile App
# Built with Flutter

name: flutter_app
description: Learn with Agrisiti - Mobile Learning Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"
dependencies:
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  analyzer: ^9.0.0
  intl: ^0.20.2
  nylo_framework: ^6.9.1
  pretty_dio_logger: ^1.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0
  font_awesome_flutter: ^10.12.0
  scaffold_ui: ^1.2.9
  video_player: ^2.9.2
  connectivity_plus: ^6.1.0
  youtube_player_flutter: ^9.0.2
  flutter_cache_manager: ^3.4.1
  chewie: ^1.8.0
  file_picker: ^10.3.10
  image_picker: ^1.1.2
  share_plus: ^10.1.2
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  pusher_channels_flutter: ^2.2.1
  youtube_explode_dart: ^2.0.0
  flutter_downloader: ^1.11.7
  permission_handler: ^11.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
#  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/app_icon/icon.png"
  remove_alpha_ios: true

# RENAME YOUR PROJECT
# flutter pub run rename setAppName --targets ios,android --value "YourAppName"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/images/
    - public/app_icon/
    - lang/
    - .env
